# Generated by Django 4.2.29 on 2026-07-19 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flags', '0008_featureflag_multivariate_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('change_action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('rollback', 'Rollback')], max_length=20)),
                ('source_version_no', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-version_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='featureflag',
            constraint=models.UniqueConstraint(fields=('owner', 'key'), name='unique_flag_per_owner'),
        ),
        migrations.AddField(
            model_name='flagversion',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flag_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flagversion',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='flags.featureflag'),
        ),
        migrations.AddIndex(
            model_name='flagversion',
            index=models.Index(fields=['flag', '-version_no'], name='flag_version_flag_no_idx'),
        ),
        migrations.AddConstraint(
            model_name='flagversion',
            constraint=models.UniqueConstraint(fields=('flag', 'version_no'), name='unique_version_per_flag'),
        ),
    ]
