# Generated by Django 4.2.29 on 2026-08-02 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('flags', '0009_flagversion_featureflag_unique_flag_per_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='organizations.project'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to=settings.AUTH_USER_MODEL),
        ),
    ]
