# Generated by Django 4.2.29 on 2026-08-02 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_backfill_personal_orgs'),
        ('flags', '0010_featureflag_project_alter_featureflag_owner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='featureflag',
            name='unique_flag_per_owner',
        ),
        migrations.RemoveField(
            model_name='featureflag',
            name='owner',
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='key',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='organizations.project'),
        ),
        migrations.AddConstraint(
            model_name='featureflag',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='unique_flag_per_project'),
        ),
    ]
