# Generated by Django 4.2.29 on 2026-08-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0011_remove_featureflag_unique_flag_per_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagTarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_key', models.CharField(max_length=255)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='flags.featureflag')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='flags.variation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='flagtarget',
            constraint=models.UniqueConstraint(fields=('flag', 'user_key'), name='unique_target_per_flag_user'),
        ),
    ]
