# Generated by Django 4.2.29 on 2026-08-22 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0012_flagtarget_flagtarget_unique_target_per_flag_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagPrerequisite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='flags.featureflag')),
                ('prerequisite_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='flags.featureflag')),
                ('required_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='flags.variation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='flagprerequisite',
            constraint=models.UniqueConstraint(fields=('flag', 'prerequisite_flag'), name='unique_prerequisite_per_flag'),
        ),
        migrations.AddConstraint(
            model_name='flagprerequisite',
            constraint=models.CheckConstraint(check=models.Q(('flag', models.F('prerequisite_flag')), _negated=True), name='prerequisite_is_not_self'),
        ),
    ]
