# Generated by Django 4.2.29 on 2026-08-22 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_backfill_personal_orgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('key', models.SlugField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='organizations.project')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentTarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_key', models.CharField(max_length=255)),
                ('excluded', models.BooleanField(default=False)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='segments.segment')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('neq', 'Not Equals'), ('contains', 'Contains'), ('in', 'In'), ('not_in', 'Not In'), ('gt', 'Greater Than'), ('lt', 'Less Than')], max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='segments.segment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='segmenttarget',
            constraint=models.UniqueConstraint(fields=('segment', 'user_key'), name='unique_segment_target_per_user'),
        ),
        migrations.AddIndex(
            model_name='segmentrule',
            index=models.Index(fields=['segment'], name='segment_rule_segment_idx'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='unique_segment_per_project'),
        ),
    ]
