# Generated by Django 4.2.29 on 2026-08-02 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='organizations.project'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='environment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='environmentflag',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
