# Generated by Django 4.2.29 on 2026-08-02 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_backfill_personal_orgs'),
        ('environment', '0002_environment_project_alter_environment_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='environment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='organizations.project'),
        ),
        migrations.AlterUniqueTogether(
            name='environment',
            unique_together={('project', 'name')},
        ),
        migrations.RemoveField(
            model_name='environment',
            name='owner',
        ),
    ]
