# Generated by Django 4.2.30 on 2026-09-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_alter_environment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='config_version',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
