# Generated by Django 4.2.30 on 2026-09-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdk_keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdkkey',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
