# Generated by Django 4.2.30 on 2026-09-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
