# Generated by Django 4.2.29 on 2026-03-03 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.featureflag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
