# Generated by Django 4.2.29 on 2026-08-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0012_flagtarget_flagtarget_unique_target_per_flag_user'),
        ('rules', '0004_rule_serve_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='flags.featureflag'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='operator',
            field=models.CharField(choices=[('eq', 'Equals'), ('neq', 'Not Equals'), ('contains', 'Contains'), ('in', 'In'), ('not_in', 'Not In'), ('gt', 'Greater Than'), ('lt', 'Less Than'), ('in_segment', 'In Segment'), ('not_in_segment', 'Not In Segment')], max_length=50),
        ),
    ]
