# Generated by Django 4.2.29 on 2026-08-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_alter_rule_flag_alter_rule_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='attribute',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
