# Generated by Django 4.2.29 on 2026-08-22 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_alter_rule_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rollout_percentage',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='rule',
            constraint=models.CheckConstraint(check=models.Q(('rollout_percentage__gte', 0), ('rollout_percentage__lte', 100)), name='rules_rule_rollout_percentage_0_100'),
        ),
    ]
